version: "3"
services:
  portfolio:
    container_name: portfolio
    build: .
    restart: always
    env_file:
      - .env
    environment:
      - FLASK_APP=flask/server.py
    ports:
      - "5000:5000"
    depends_on:
      - mysql

  mysql:
    container_name: mysql
    image: mariadb
    restart: always
    env_file:
      - .env
    volumes:
      - mydatabase:/var/lib/mysql

volumes:
  mydatabase:
