name: Run Tests
on:
  push:
    branches:
      - main
    pull_request:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    name: Run Tests
    env:
      TESTING: true
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10.4"

      - name: Setup Python Virtual Env
        run: |
          cd flask
          python3 -m venv venv

      - name: Install Dependencies
        run: |
          cd flask
          venv/bin/pip install -r requirements.txt

      - name: Run Tests
        run: |
          cd flask
          ./run_test.sh
